kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nodeport-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31000
        hostPort: 31000
        protocol: TCP