
apiVersion: v1
kind: Pod
metadata:
  name: busybox-teste
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      tty: true
      stdin: true
