apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
  namespace: default
  uid: 82bf552a-b151-4bba-91fb-9d2aedc0ea5d
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: meu-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meu-app
    spec:
      containers:
      - image: nginx:1.16
        name: meu-app
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
